import fs from "fs";
import path from "path";

/**
 * CONFIG PATHS
 */
const CONTENT_DIR = path.resolve("contents"); // where profiles/languages/contentType live
const DATA_DIR = path.resolve("src/data"); // output directory for generated TS files
const REGISTRY_FILE = path.join(DATA_DIR, "registry.ts");
const CONFIG_FILE = path.resolve("src/data/configs.json"); // new config location

/**
 * TYPES
 */
type Registry = Record<
  string, // profile
  Record<
    string, // language
    Record<string, string> // contentType -> importPath
  >
>;

/**
 * HELPERS
 */
function isDir(p: string) {
  return fs.existsSync(p) && fs.statSync(p).isDirectory();
}

function readDirs(p: string): string[] {
  return fs.existsSync(p)
    ? fs.readdirSync(p).filter((d) => isDir(path.join(p, d)))
    : [];
}

function readConfig(): { defaultLanguage: string; allowedLanguages: string[] } {
  if (!fs.existsSync(CONFIG_FILE)) throw new Error("configs.json not found");
  const raw = JSON.parse(fs.readFileSync(CONFIG_FILE, "utf-8"));
  const { defaultLanguage, allowedLanguages } = raw.languages;
  return { defaultLanguage, allowedLanguages };
}

/**
 * BUILD REGISTRY OBJECT
 */
function buildRegistry(): Registry {
  const { allowedLanguages } = readConfig();
  const allowedSet = new Set(allowedLanguages);
  const registry: Registry = {};

  for (const profile of readDirs(CONTENT_DIR)) {
    const profilePath = path.join(CONTENT_DIR, profile);
    registry[profile] = {};

    for (const lang of readDirs(profilePath)) {
      if (!allowedSet.has(lang)) {
        console.warn(
          `⚠️  Skipping language "${lang}" (not in allowedLanguages)`,
        );
        continue;
      }

      const langPath = path.join(profilePath, lang);
      registry[profile][lang] = {};

      for (const contentType of readDirs(langPath)) {
        const importPath = `./${profile}/${lang}/${contentType}`;
        registry[profile][lang][contentType] = importPath;
      }

      if (Object.keys(registry[profile][lang]).length === 0) {
        delete registry[profile][lang];
      }
    }

    if (Object.keys(registry[profile]).length === 0) {
      delete registry[profile];
    }
  }

  return registry;
}

/**
 * GENERATE registry.ts SOURCE
 */
function generateRegistryTS(registry: Registry): string {
  const lines: string[] = [];
  lines.push("/* AUTO-GENERATED FILE — DO NOT EDIT */");
  lines.push("/* Generated by scripts/generate-registry.ts */\n");
  lines.push("export const registry = {");

  for (const [profile, langs] of Object.entries(registry)) {
    lines.push(`  ${profile}: {`);

    for (const [lang, types] of Object.entries(langs)) {
      lines.push(`    ${lang}: {`);

      for (const [type, importPath] of Object.entries(types)) {
        lines.push(`      ${type}: () => import("${importPath}"),`);
      }

      lines.push("    },");
    }

    lines.push("  },");
  }

  lines.push("} as const;\n");
  lines.push("export type Registry = typeof registry;\n");

  return lines.join("\n");
}

/**
 * MAIN
 */
export function generateRegistry() {
  const registry = buildRegistry();
  const output = generateRegistryTS(registry);

  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(REGISTRY_FILE, output, "utf-8");

  console.log("✅ data/registry.ts generated successfully");
}
