import fs from "fs";
import path from "path";

type BlogListItem = {
  id: number | string;
};

type BlogPost = {
  lang: string;
  id: string;
};

const DATA_DIR = path.join(process.cwd(), "src/data");
const OUTPUT_FILE = path.join(DATA_DIR, "blog-posts.ts");

/**
 * Reads all src/data/<lang>/blog_list.json
 * and generates src/data/blog-posts.ts
 */
export function generateBlogPostsSlug(): void {
  console.log("🚀 Starting Blog Posts generation...");

  const languages = fs
      .readdirSync(DATA_DIR, { withFileTypes: true })
      .filter((dir) => dir.isDirectory())
      .map((dir) => dir.name);

  if (languages.length === 0) {
    console.error("❌ No language directories found in src/data/");
    process.exit(1);
  }

  console.log(`📁 Found languages: ${languages.join(", ")}`);

  const blogPosts: BlogPost[] = [];

  for (const lang of languages) {
    const blogListPath = path.join(DATA_DIR, lang, "blog_list.json");

    if (!fs.existsSync(blogListPath)) {
      console.log(`   ⚠ Skipping ${lang} (no blog_list.json)`);
      continue;
    }

    const raw = fs.readFileSync(blogListPath, "utf-8");
    const items: BlogListItem[] = JSON.parse(raw);

    items.forEach((item) => {
      blogPosts.push({
        lang,
        id: String(item.id),
      });
    });

    console.log(`   ✓ ${lang}: ${items.length} blog(s)`);
  }

  const fileContent = `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by generateBlogPostsSlug()

export const blogPosts = ${JSON.stringify(blogPosts, null, 2)} as const;
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, "utf-8");

  console.log("\n✅ Blog posts generated successfully!");
  console.log(`📄 Output: ${OUTPUT_FILE}`);
  console.log(`📊 Total posts: ${blogPosts.length}`);
}
