import fs from "fs";
import path from "path";
import { ContentsService } from "@/lib/services/contents.service";

/* ---------------------------------- Types --------------------------------- */

type BlogPost = {
  id: number | string;
};

type BlogSlug = {
  profile: string;
  lang: string;
  id: number;
};

/* -------------------------------- Constants ------------------------------- */

const DATA_DIR = path.join(process.cwd(), "src/data/contents");

const OUTPUT_DIR = path.join(process.cwd(), "src/data/configs/generated");

const OUTPUT_FILE = path.join(OUTPUT_DIR, "blog-posts-slugs-profile.ts");

/* ------------------------- TS Literal Serializer --------------------------- */

function toTsLiteral(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `[\n${value
      .map((v) => `${pad}  ${toTsLiteral(v, indent + 1)}`)
      .join(",\n")}\n${pad}]`;
  }

  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value).map(
      ([k, v]) => `${pad}  ${k}: ${toTsLiteral(v, indent + 1)}`,
    );
    return `{\n${entries.join(",\n")}\n${pad}}`;
  }

  if (typeof value === "string") {
    return `"${value}"`;
  }

  return String(value);
}

/* ------------------------------ Generator --------------------------------- */

export async function generateBlogPostsSlugsSlug() {
  console.log("🚀 Starting blog posts slug generation...");

  const blogPostsSlugs: BlogSlug[] = [];

  if (!fs.existsSync(DATA_DIR)) {
    console.warn(`⚠ DATA_DIR does not exist: ${DATA_DIR}`);
    return;
  }

  const profiles = fs
    .readdirSync(DATA_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const profile of profiles) {
    const profileDir = path.join(DATA_DIR, profile);

    const languages = fs
      .readdirSync(profileDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);

    if (languages.length === 0) {
      console.warn(`⚠ No languages found for profile: ${profile}`);
      continue;
    }

    for (const lang of languages) {
      const blogList = await ContentsService.loadContentOf<BlogPost[]>(
        profile,
        lang,
        "blog_list",
        [],
      );

      blogList.forEach((item) => {
        blogPostsSlugs.push({
          profile,
          lang,
          id: Number(item.id),
        });
      });

      console.log(`✓ ${profile}/${lang}: ${blogList.length} blog(s)`);
    }
  }

  /* --------------------------- Deterministic sort -------------------------- */

  blogPostsSlugs.sort(
    (a, b) =>
      a.profile.localeCompare(b.profile) ||
      a.lang.localeCompare(b.lang) ||
      a.id - b.id,
  );

  /* ------------------------------ File write ------------------------------- */

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const fileContent = `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by generateBlogPostsSlugsSlug()

export const blogPostsSlugsProfile = ${toTsLiteral(blogPostsSlugs)} as const;
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, "utf-8");

  console.log("\n✅ Blog post slugs generated successfully");
  console.log(`📄 Output: ${OUTPUT_FILE}`);
  console.log(`📊 Total posts: ${blogPostsSlugs.length}`);
}
