import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";
import { toTsObject } from "@/lib/scripts/helpers/to-ts-helper";

const CONTENT_ROOT = path.join(process.cwd(), "src/data/contents");
const OUTPUT_DIR = path.join(process.cwd(), "src/data/configs/generated");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "content-item-counts.ts");

type Counts = Record<
  string, // profile
  Record<
    string, // language
    Record<string, number> // content_key -> count
  >
>;

/**
 * Safely loads a TS module and extracts its exported data.
 */
async function loadData(filePath: string): Promise<unknown | null> {
  try {
    const fileUrl = pathToFileURL(filePath).href;
    const mod = await import(fileUrl);

    return mod.data ?? mod.default ?? null;
  } catch {
    return null;
  }
}

/**
 * Resolves item count from a content file.
 */
function resolveCount(value: unknown): number {
  if (Array.isArray(value)) {
    return value.length;
  }

  if (typeof value === "object" && value !== null) {
    return Object.keys(value).length;
  }

  return 0;
}

async function generate() {
  const result: Counts = {};

  if (!fs.existsSync(CONTENT_ROOT)) {
    throw new Error("Content root directory does not exist.");
  }

  const profiles = fs.readdirSync(CONTENT_ROOT);

  for (const profile of profiles) {
    const profilePath = path.join(CONTENT_ROOT, profile);
    if (!fs.statSync(profilePath).isDirectory()) continue;

    result[profile] = {};

    const languages = fs.readdirSync(profilePath);

    for (const lang of languages) {
      const langPath = path.join(profilePath, lang);
      if (!fs.statSync(langPath).isDirectory()) continue;

      result[profile][lang] = {};

      const files = fs.readdirSync(langPath).filter((f) => f.endsWith(".ts"));

      for (const file of files) {
        const key = file.replace(/\.ts$/, "");
        const filePath = path.join(langPath, file);

        const data = await loadData(filePath);
        const count = resolveCount(data);

        result[profile][lang][key] = count;
      }
    }
  }

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const ts = `// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-content-item-counts.ts

export const CONTENT_ITEM_COUNTS = ${toTsObject(result)} as const;
`.trim();

  fs.writeFileSync(OUTPUT_FILE, ts, "utf-8");

  console.log("✔ content-item-counts.ts generated successfully");
}

function main(): void {
  generate().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

export function generateContentItemCounts() {
  main();
}
