import fs from "fs";
import path from "path";
import {ContentsService} from "@/lib/services/contents.service";

type BlogPost = {
    profile: string;
    lang: string;
    id: string;
};

const DATA_DIR = path.join(process.cwd(), "src/data/contents");
const outputDir = path.join(
    process.cwd(),
    "src/data/configs/generated"
);

const outputFile = path.join(
    outputDir,
    "blog-posts-slugs-profile.ts"
);
const OUTPUT_FILE = path.join(process.cwd(), "src/data/configs/blog-posts-slugs-p.ts");

/**
 * Reads all src/data/<lang>/blog_list.json
 * and generates src/data/blog-posts-slugs.ts
 */
export async function generateBlogPostsSlugsSlug() {
    console.log("🚀 Starting Blog Posts generation...");

    const blogPostsSlugs: BlogPost[] = [];

    const profiles = fs
        .readdirSync(DATA_DIR, {withFileTypes: true})
        .filter((dir) => dir.isDirectory())
        .map((dir) => dir.name);

    console.log("🚀 profiles--", profiles);

    for (const profile of profiles) {

        const languages = fs
            .readdirSync(DATA_DIR + "/" + profile, {withFileTypes: true})
            .filter((dir) => dir.isDirectory())
            .map((dir) => dir.name);

        console.log("🚀 languages--", languages);

        if (languages.length === 0) {
            console.error("❌ No language directories found in " + DATA_DIR);
            process.exit(1);
        }

        console.log(`📁 Found languages: ${languages.join(", ")}`);


        for (const lang of languages) {
            const blog_list = await ContentsService.loadContentOf<BlogPost[]>(
                profile,
                lang,
                "blog_list"
            );
            console.log(`📁 Found profile: `, profile);
            console.log(`📁 Found lang: `, lang);
            //console.log(`📁 Found blog_list: `, JSON.stringify(blog_list));

            blog_list.forEach((item) => {
                blogPostsSlugs.push({
                    profile,
                    lang,
                    id: item.id,
                });
            });

            console.log(`   ✓ ${lang}: ${blog_list.length} blog(s)`);
        }
    }
    console.log(`📁 Found blogPostsSlugs: `, blogPostsSlugs);

    const fileContent = `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by generateBlogPostsSlugsSlug()

export const blogPostsSlugsProfile = ${JSON.stringify(blogPostsSlugs, null, 2)} as const;
`;
    console.log(`📄 Output: ${outputFile}`);
    // Ensure directory exists
    fs.mkdirSync(outputDir, {recursive: true});

    fs.writeFileSync(outputFile, fileContent, "utf-8");

    console.log("\n✅ Blog posts generated successfully!");
    console.log(`📄 Output: ${outputFile}`);
    console.log(`📊 Total posts: ${blogPostsSlugs.length}`);
}
