// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by generateBlogPostsSlugsSlug()

export const blogPostsSlugs = [
  {
    "lang": "en",
    "id": "1"
  },
  {
    "lang": "en",
    "id": "2"
  },
  {
    "lang": "en",
    "id": "3"
  },
  {
    "lang": "en",
    "id": "4"
  },
  {
    "lang": "en",
    "id": "5"
  },
  {
    "lang": "en",
    "id": "6"
  },
  {
    "lang": "en",
    "id": "7"
  },
  {
    "lang": "en",
    "id": "8"
  },
  {
    "lang": "en",
    "id": "9"
  },
  {
    "lang": "en",
    "id": "10"
  },
  {
    "lang": "en",
    "id": "11"
  },
  {
    "lang": "en",
    "id": "12"
  },
  {
    "lang": "fr",
    "id": "15"
  },
  {
    "lang": "fr",
    "id": "2"
  },
  {
    "lang": "fr",
    "id": "3"
  },
  {
    "lang": "fr",
    "id": "4"
  },
  {
    "lang": "fr",
    "id": "5"
  },
  {
    "lang": "fr",
    "id": "6"
  },
  {
    "lang": "fr",
    "id": "7"
  },
  {
    "lang": "fr",
    "id": "8"
  },
  {
    "lang": "fr",
    "id": "9"
  },
  {
    "lang": "fr",
    "id": "10"
  },
  {
    "lang": "fr",
    "id": "11"
  },
  {
    "lang": "fr",
    "id": "12"
  },
  {
    "lang": "fr",
    "id": "13"
  },
  {
    "lang": "fr",
    "id": "15"
  }
] as const;
