import {
  AlertCircle,
  ArrowRight,
  Award,
  BarChart,
  Book,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  CheckCircle,
  ChevronRight,
  Clock,
  Cloud,
  Code,
  Coffee,
  Cookie,
  Database,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Github,
  Globe,
  GraduationCap,
  Heart,
  Link,
  Linkedin,
  Lock,
  LucideIcon,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Music,
  Palette,
  Pen,
  Plane,
  Quote,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Twitter,
  UserCheck,
  Users,
  Video,
  Wrench,
  Zap,
  ArrowLeft,
  Share2,
  Tag,
  ChevronLeft,
  Phone,
  Send,
  Instagram,
  Facebook,
  X,
  Image as ImageIcon,
  Grid3x3,
  Layers,
  Printer,
  HeadphonesIcon,
  ThumbsUp,
  Monitor,
  Moon,
  Sun,
  FileUser,
  Home,
  User,
} from "lucide-react"; // Icon mapping

// Icon mapping for dynamic lookup
const ICON_MAP: { [key: string]: LucideIcon } = {
  user: User,
  home: Home,
  "file-user": FileUser,
  monitor: Monitor,
  moon: Moon,
  sun: Sun,
  "thumbs-up": ThumbsUp,
  "headphones-icon": HeadphonesIcon,
  printer: Printer,
  layers: Layers,
  grid3x3: Grid3x3,
  x: X,
  "image-icon": ImageIcon,
  phone: Phone,
  send: Send,
  instagram: Instagram,
  facebook: Facebook,
  tag: Tag,
  share2: Share2,
  "arrow-left": ArrowLeft,
  zap: Zap,
  quote: Quote,
  link: Link,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "trending-up": TrendingUp,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  sparkles: Sparkles,
  star: Star,
  building2: Building2,
  "external-link": ExternalLink,
  trophy: Trophy,
  eye: Eye,
  cookie: Cookie,
  "user-check": UserCheck,
  mail: Mail,
  code: Code,
  palette: Palette,
  smartphone: Smartphone,
  database: Database,
  cloud: Cloud,
  search: Search,
  megaphone: Megaphone,
  "bar-chart": BarChart,
  pen: Pen,
  video: Video,
  "shopping-cart": ShoppingCart,
  users: Users,
  settings: Settings,
  technical: Code,
  design: Palette,
  business: TrendingUp,
  "soft-skills": MessageSquare,
  languages: MessageSquare,
  tools: Wrench,
  fileText: FileText,
  "dollar-sign": DollarSign,
  lock: Lock,
  clock: Clock,
  "alert-circle": AlertCircle,
  shield: Shield,
  "file-text": FileText,
  "check-circle": CheckCircle,
  download: Download,
  "arrow-right": ArrowRight,
  "brief-case": Briefcase,
  target: Target,
  heart: Heart,
  award: Award,
  calendar: Calendar,
  music: Music,
  camera: Camera,
  book: Book,
  plane: Plane,
  coffee: Coffee,
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  globe: Globe,
  "map-pin": MapPin,
};

export const showLucidIcon = (
  icon: string,
  cssClass = "w-5 h-5 text-primary",
  size?: string | number,
) => {
  const IconComponent = ICON_MAP[icon.toLowerCase()];
  // console.log(icon, IconComponent)
  if (size) {
    return <IconComponent className={cssClass} size={size} />;
  } else {
    return <IconComponent className={cssClass} />;
  }
};
