"use client";

import React from 'react';
import {
    AlertCircle,
    Award,
    BarChart,
    Book,
    Briefcase,
    Calendar,
    Camera,
    CheckCircle,
    Clock,
    Cloud,
    Code,
    Coffee,
    Cookie,
    Database,
    DollarSign,
    Eye,
    FileText,
    Github,
    Globe,
    Heart,
    Linkedin,
    Lock,
    LucideIcon,
    Mail,
    MapPin,
    Megaphone,
    MessageSquare,
    Music,
    Palette,
    Pen,
    Plane,
    Search,
    Settings,
    Shield,
    ShoppingCart,
    Smartphone,
    Target,
    TrendingUp,
    Twitter,
    UserCheck,
    Users,
    Video,
    Wrench,
    Download,
    ArrowRight,
    Building2,
    ExternalLink,
    Trophy,
    Star,
    Sparkles
} from 'lucide-react'; // Icon mapping

// Icon mapping for dynamic lookup
export const ICON_MAP: { [key: string]: LucideIcon } = {
    'sparkles': Sparkles,
    'star': Star,
    'building2': Building2,
    'external-link': ExternalLink,
    'trophy': Trophy,
    'eye': Eye,
    'cookie': Cookie,
    'user-check': UserCheck,
    'mail': Mail,
    'code': Code,
    'palette': Palette,
    'smartphone': Smartphone,
    'database': Database,
    'cloud': Cloud,
    'search': Search,
    'megaphone': Megaphone,
    'bar-chart': BarChart,
    'pen': Pen,
    'video': Video,
    'shopping-cart': ShoppingCart,
    'users': Users,
    'settings': Settings,
    'technical': Code,
    'design': Palette,
    'business': TrendingUp,
    'soft-skills': MessageSquare,
    'languages': MessageSquare,
    'tools': Wrench,
    'fileText': FileText,
    'dollar-sign': DollarSign,
    'lock': Lock,
    'clock': Clock,
    'alert-circle': AlertCircle,
    'shield': Shield,
    'file-text': FileText,
    'check-circle': CheckCircle,
    'download': Download,
    'arrow-right': ArrowRight,
    'briefcase': Briefcase,
    'target': Target,
    'heart': Heart,
    'award': Award,
    'calendar': Calendar,
    'music': Music,
    'camera': Camera,
    'book': Book,
    'plane': Plane,
    'coffee': Coffee,
    'github': Github,
    'linkedin': Linkedin,
    'twitter': Twitter,
    'globe': Globe,
    'map-pin': MapPin,
};

export const showLucidIcon = (icon: string, cssClass='w-5 h-5 text-primary') => {
    const IconComponent = ICON_MAP[icon];
    return <IconComponent className={cssClass}/>;
};